CREATE TABLE "property" (
  "property_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_id" INTEGER NOT NULL,
  "room_count" INTEGER NOT NULL,
  "daily_rent" REAL NOT NULL DEFAULT 0,
  "neighborhood" VARCHAR(100) NOT NULL DEFAULT '',
  "description" TEXT NOT NULL
);

CREATE TABLE "availability" (
  "availability_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "property_id" INTEGER NOT NULL,
  "start_date" DATE DEFAULT CURRENT_TIMESTAMP,
  "end_date" DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "photo" (
  "photo_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "property_id" INTEGER NOT NULL,
  "url" VARCHAR(255) NOT NULL DEFAULT 'error.png'
);

CREATE TABLE "property_type" (
  "type_id" INTEGER PRIMARY KEY NOT NULL,
  "type_name" VARCHAR(50) NOT NULL
);

CREATE TABLE "rental" (
  "rental_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "property_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  "start_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "end_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "reservation_date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "favorites" (
  "property_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  PRIMARY KEY ("property_id", "user_id")
);

ALTER TABLE "property" 
ADD CONSTRAINT "fk_property_type" FOREIGN KEY ("type_id") REFERENCES "property_type" ("type_id");

ALTER TABLE "rental" 
ADD CONSTRAINT "fk_rental_user" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "property" 
ADD CONSTRAINT "fk_property_rental" FOREIGN KEY ("property_id") REFERENCES "rental" ("property_id");

ALTER TABLE "photo" 
ADD CONSTRAINT "fk_photo_property" FOREIGN KEY ("property_id") REFERENCES "property" ("property_id");

ALTER TABLE "favorites" 
ADD CONSTRAINT "fk_favorites_property" FOREIGN KEY ("property_id") REFERENCES "property" ("property_id");

ALTER TABLE "favorites" 
ADD CONSTRAINT "fk_favorites_user" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "availability" 
ADD CONSTRAINT "fk_availability_property" FOREIGN KEY ("property_id") REFERENCES "property" ("property_id");
