CREATE TABLE "habitation" (
  "id_habitation" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_type" integer NOT NULL,
  "nb_rooms" integer NOT NULL,
  "daily_rent" float NOT NULL DEFAULT 0,
  "neighborhood" varchar(100) NOT NULL DEFAULT '',
  "description" text NOT NULL
);

CREATE TABLE "photo" (
  "id_photo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_habitation" integer NOT NULL,
  "link" varchar(255) NOT NULL DEFAULT 'error.png'
);

CREATE TABLE "type" (
  "id_type" integer PRIMARY KEY NOT NULL,
  "type_name" integer NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR(50) UNIQUE NOT NULL,
  "email" VARCHAR(100) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "is_admin" BOOLEAN NOT NULL DEFAULT false,
  "created_at" DATETIME DEFAULT (CURRENT_TIMESTAMP),
  "photo" varchar(255)
);

CREATE TABLE "rental" (
  "id_rental" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_habitation" integer NOT NULL,
  "id_user" integer NOT NULL,
  "start_date" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "end_date" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "reservation_date" date NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "like" (
  "id_habitation" integer NOT NULL,
  "id_users" integer NOT NULL,
  PRIMARY KEY ("id_habitation", "id_users")
);

ALTER TABLE "habitation" ADD CONSTRAINT "fktype" FOREIGN KEY ("id_type") REFERENCES "type" ("id_type");

ALTER TABLE "rental" ADD CONSTRAINT "fkuser" FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "habitation" ADD CONSTRAINT "fkhabitation" FOREIGN KEY ("id_habitation") REFERENCES "rental" ("id_habitation");

ALTER TABLE "photo" ADD CONSTRAINT "fkphoto" FOREIGN KEY ("id_habitation") REFERENCES "habitation" ("id_habitation");

ALTER TABLE "like" ADD CONSTRAINT "fkhabitationlike" FOREIGN KEY ("id_habitation") REFERENCES "habitation" ("id_habitation");

ALTER TABLE "like" ADD CONSTRAINT "fkuserlike" FOREIGN KEY ("id_users") REFERENCES "users" ("id");
